{"trial_id": "4", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "optimizer", "default": "Adam", "conditions": [], "values": ["Adam", "SGD", "RMSprop", "AdamW", "Adadelta", "Adagrad", "Adamax", "Adafactor", "Nadam", "Ftrl"], "ordered": false}}], "values": {"optimizer": "AdamW"}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"c:\\Users\\SDS\\.conda\\envs\\test2\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 273, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\SDS\\.conda\\envs\\test2\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 238, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\SDS\\.conda\\envs\\test2\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"c:\\Users\\SDS\\.conda\\envs\\test2\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 232, in _build_and_fit_model\n    model = self._try_build(hp)\n  File \"c:\\Users\\SDS\\.conda\\envs\\test2\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 164, in _try_build\n    model = self._build_hypermodel(hp)\n  File \"c:\\Users\\SDS\\.conda\\envs\\test2\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 155, in _build_hypermodel\n    model = self.hypermodel.build(hp)\n  File \"C:\\Users\\SDS\\AppData\\Local\\Temp\\ipykernel_11044\\3521053754.py\", line 6, in bulid_model\n    model1.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])\n  File \"c:\\Users\\SDS\\.conda\\envs\\test2\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"c:\\Users\\SDS\\.conda\\envs\\test2\\lib\\site-packages\\keras\\src\\saving\\legacy\\serialization.py\", line 365, in class_and_config_for_serialized_keras_object\n    raise ValueError(\nValueError: Unknown optimizer: 'AdamW'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.\n"}